name: tiny_music
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_screenutil: ^5.8.4
  just_audio: ^0.9.34
  flutter_svg: ^2.0.7
  dio: ^5.2.1+1
  hive: ^2.2.3
  connectivity_plus: ^4.0.1
  bot_toast: ^4.0.4
  lottie: ^2.4.0
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  audio_video_progress_bar: ^1.0.1
  just_audio_background:
    git:
      url: https://github.com/zhcode-fun/just_audio.git
      path: just_audio_background
      ref: minor
  hive_generator: ^2.0.0
  cached_network_image: ^3.2.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # flutter_launcher_icons: ^0.13.1
  # flutter_native_splash: ^2.3.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/navidrome_logo.svg
    - images/music.svg
    - images/album.svg
    - images/radio.svg
    - images/singer.svg
    - images/song_collection.svg
    - images/setting.svg
    - images/search.svg
    - images/song_list.svg
    - images/default_cover.png
    - images/spinner.json
